handler/blob.go, handler/image.go, handler/manifests.go, handler/repository.go, handler/users.go
Support Docker V1 login protocol,fix some compiling bugs, and optimize the JSOM description of function.
=> Support Docker V1 login protocol and fix bugs

handler/users.go
Temporarily do not achieve v1 login function,delete reference code
=> Update v1 login codes

README.md, middleware/header.go
Update the runtime.conf example in the README.md
```
registry = 0.9
distribution = registry/2.0
standalone = true
```
=> Use wrench setting of registry/distribution/standalone value

handler/ping.go, middleware/header.go
Set different return with check Authorization in request header result.
=> Add WWW-Authenticate to the Resp header

handler/ping.go, middleware/header.go, models/image.go
Fix some bugs for V2 push and pull
=> Fix some bugs for V2 push and pull

handler/image.go, handler/manifests.go, handler/repository.go, models/image.go, models/repo.go
Use log function of Beego to instead of fmt output
=> Update the expression of log output

handler/manifests.go, models/repo.go
Add V2 taglist function to support docker pull command with -a option
=> Add V2 taglist function to support docker pull command with -a option

handler/blob.go, handler/manifests.go
Compatible with V1,save the layerfile by imageId as the same with V1
=> Compatible with V1,save the layerfile by imageId as the same with V1

README.md, handler/blob.go, handler/manifests.go, handler/repository.go, middleware/header.go, middleware/middleware.go
Read parameters from config instead of using const
=> Read parameters from config instead of using const

handler/blob.go, handler/manifests.go, models/image.go
=> Update the tarsum calibration method

handler/blob.go, handler/image.go, handler/manifests.go, handler/repository.go, middleware/header.go, middleware/middleware.go
Bugfixed and loginfo added for Docker V2 protocol
=> bugfixed for Docker V2 protocol

handler/manifests.go, models/repo.go
Bug fixed: when multiple clients request to push repository at the same time,error occured.
=> Fix bug about doing multiple push at the same time

handler/blob.go, handler/manifests.go, middleware/header.go, models/image.go, models/repo.go, module/module.go
Fallback the function of convert temporarily
=> remove function of Docker V2 convert to V1

test/docker/docker_cli_login_test.go, test/docker/docker_cli_pull_test.go, test/docker/docker_cli_push_test.go, test/setting.go, test/utils.go
Init dockyard testsuite,make push and pull testing automatically
=> Init dockyard testsuite

test/docker/docker_cli_pull_test.go
In protocol V2,if there are multiple tags in registry and pulling is not specified tag, default to get latest tag,different from protocol V1,this situation should be covered.
=> Modify pull Test suite

handler/blob.go, handler/manifests.go
reference issue:https://github.com/containerops/dockyard/issues/42
=> Fix bug about listen mode setting is invalid in runtime.conf.fix #42

backend/backend.go, backend/drivers/native/native.go
Init native driver file of backend as default object storage method
=> Init native driver file of backend

Godeps/Godeps.json, Godeps/_workspace/src/github.com/Unknwon/macaron/README.md, cmd/web.go, handler/blob.go, handler/image.go, handler/manifests.go, handler/ping.go, handler/repository.go, handler/users.go, middleware/header.go, middleware/logger.go, middleware/middleware.go, router/router.go, web/web.go
update the import package to match new macaron path
=> Update macaron package path

cmd/web.go
Get rid of the dependence on Generator project
=> Get rid of the dependence on Generator project

backend/backend.go, backend/drivers/drivers.go, backend/drivers/native/native.go, backend/drivers/qiniu/qiniu.go, backend/drivers/upyun/upyun.go, main.go, web/web.go
Modify the method of reading config,all the config should be read in wrench
=> Optimize backend

README.md
Signed-off-by: ChengTiesheng <chengtiesheng@huawei.com>
=> And more information

handler/acidiscover.go, handler/acifetch.go, handler/acipush.go, models/acitemplate.html, router/router.go
Initialize the Dockyard support for rkt fetch and push
=> Support rkt fetch and integrate ac-server

conf/acifetchtemplate.html, conf/acipushtemplate.html, handler/acidiscover.go, handler/acifetch.go, handler/acipush.go, router/router.go
=> Optimize rkt fetch code

handler/acifetch.go, middleware/header.go, router/router.go, web/web.go
Bugfixed and code optimized for rkt fetch.
=> optimize code for rkt fetch

conf/acifetchtemplate.html, conf/acipushtemplate.html, handler/acidiscover.go, handler/acipush.go
clear all logic of acpush and make sure html template to currect way.
=> acpush optimized

oss/chunkmaster/api/chunkserver.go, oss/chunkmaster/api/chunkserver_test.go, oss/chunkmaster/api/init.go, oss/chunkmaster/metadata/metadata.go, oss/chunkmaster/metadata/mysqldriver/chunkserverdb.go, oss/chunkmaster/metadata/mysqldriver/chunkserverdb_test.go, oss/chunkmaster/metadata/mysqldriver/mysqldb.go, oss/cmd/chunkmaster/main.go, oss/logs/log.go, oss/utils/util.go
move logs and utils into oss and adjust the usage of import packages in oss
Signed-off-by: Wang Qilin <wangqilin2@huawei.com>
=> move logs and utils into oss and adjust the usage of import packages

Godeps/_workspace/src/github.com/containerops/wrench/setting/setting.go, clair/clair.go, clair/clair_test.go
Signed-off-by: liangchenye <liangchenye@huawei.com>
The 'Clair' service is done and pass the local test with my layer.tar.
But the integration of Clair with Dockyard is not finish yet.
I'll add an 'issue' to describe that in the dockyard repo.
=> add Clair service to dockyard, update the wretch in godep accordingly

backend/drivers/aliyun/aliyun_test.go, backend/drivers/amazons3/amazons3_test.go, backend/drivers/qiniu/qiniu_test.go, backend/drivers/upyun/upyun_test.go
The implementation of backend was modified,so the test case need to be synchronized to modify
=> Update test case of backend

Makefile, oss/service.go
Signed-off-by: Wang Qilin <qilin.wang@huawei.com>
=> edit Makefile and fix a bug in starting service

module/module.go
=> Signature verification bugfix

handler/aci.go, handler/discovery.go, handler/manifests.go, middleware/notifications/noticehandler.go, models/aci.go, models/image.go, models/repo.go, module/module.go, router/router.go, views/aci/index.html
=> Fix optimization and bug

handler/aci.go, handler/discovery.go, models/aci.go, router/router.go, views/aci/index.html
=> Reformat router of rkt storage

oss/README.md
Update README of OSS, to consistent with current version
=> Update README of OSS

CHANGELOG.md, README.md
=> Update the document to prepare releasing 0.5.0 version

README.md
=> Add an example in README.md to show how to configure database

models/image.go, models/models.go, models/repository.go, models/tag.go, web/web.go
=> New support redis and orm driver

clair/channel.go, clair/clair.go, clair/clair_test.go
Signed-off-by: liangchenye <liangchenye@huawei.com>
Works in my test: add put/get interface to scan docker v2 image.
TODO:
1. we need to add a specific clair upstream version to 'Godeps'
2. take to @ChengTiesheng about the integrate with his work.
And there will be other patches to support:
1. v1 image
2. aci image
=> Clair integration

backend/drivers/oss/oss.go, backend/drivers/oss/oss_test.go
Signed-off-by: ChengTiesheng <chengtiesheng@huawei.com>
=> Fix oss driver bug

backend/backend.go, web/web.go
=> Fix bugs about backend init and config

README.md
=> Update db config description in README.md

oss/INSTALL_CN.md, oss/scripts/oss.sql
Signed-off-by: Wang Qilin <qilin.wang@huawei.com>
=> add chinese version install guide of OSS

backend/backend.go, backend/rados/error.go, backend/rados/fileinfo.go, backend/rados/rados.go, backend/rados/rados_test.go, backend/rados/uuid.go, backend/rados/uuid_test.go, utils/setting/setting.go
=> Add rados driver

backend/qiniu/qiniu.go, backend/rados/rados_test.go, bttracker/trackerserver_test.go, handler/blob.go, handler/manifests.go, module/docker.go, utils/setting/setting.go
=> Make backend be enable in Dockayrd

README.md
Signed-off-by: Meaglith Ma <genedna@gmail.com>
=> The OCI Image Spec already build

utils/db/orm/ormdriver.go
=> Support to create special database automatically if it is not existed

updater/client/command.go, updater/server/handler/appV1.go, updater/server/main.go, updater/server/utils/protocal.go, updater/server/utils/protocal/appV1/appV1.go, updater/server/utils/protocal/appV1/appV1_test.go, updater/server/utils/storage.go, updater/server/utils/storage/local/local.go, updater/server/utils/storage/local/local_test.go
add an interface to support different storage type, now only support 'local' file system'.
Will use database one the first integration is done.
Fix the client bug.
=> server list is done

cmd/database.go, cmd/web.go, updater/client/command.go, updater/server/main.go
return the error message since dockyard is using the new cli lib.
=> update cli returned error

updater/server/utils/key.go, updater/server/utils/key_test.go, updater/server/utils/km/local/local.go, updater/server/utils/km/local/local_test.go
Provide priv/pub key for a new local key manager user.
Add testcase accordingly.
=> generate key pair in key manager local mode

updater/client/README.md, updater/client/command.go, updater/client/completions/bash/duc, updater/client/main.go, updater/client/man/duc.1.md, updater/client/utils/config.go, updater/client/utils/config_test.go, updater/client/utils/repo.go, updater/client/utils/repo/appV1/appV1.go, updater/duf_test.sh
- finish command line usage in client
- update man page, auto complete 
- update testcase 
TODO:
merge to dockyard/cmd
Signed-off-by: David Liang <liangchenye@gmail.com>
=> finish client cmd line code/testcase/man

setting/setting.go
=> change deployment domain to optional

.travis.yml, tests/web_test.go, updateservice/us/us.go
add .travis file to check following things:
- go vet
with this pr, all our codes looks good
- golint
our codes  still need to improve, but just warning not error
- go build
make sure project could be built. NOTE, it must be done before `go test`, we will do system test later.
- go test
all unit tests are good. Still need to add system test in the future
=> add travis to do 'unittest/go vet/golint' checks

handler/webv1.go, router/router.go
Signed-off-by: Meaglith Ma <genedna@gmail.com>
=> Update the  web page & REST API routers and functions.

handler/appv1.go, models/appv1.go, models/hook.go, router/router.go, tests/unit/testdata/testmd5, tests/unit/updateservice_snapshot_appv1_test.go, tests/unit/updateservice_snapshot_snapshot_test.go, updateservice/snapshot/appv1.go, updateservice/snapshot/snapshot.go
This integration test is not done. I still did not add SQL codes.
But the unit test is done.
I added a detailed designation in #165.
=>  add snapshot service to implement scan feature

.travis.yml, handler/appcv1.go, tests/unit/updateservice_snapshot_bycontainer_test.go
check if signed-off-by information is added in each commit.
=> check signed-off-by info in each commit
